spring:
  datasource:
    url: ${SONG_DB_DATASOURCE_URL:jdbc:postgresql://localhost:5433/song-db}
    username: postgres
    password: postgres
  application:
    name: song-service
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_APP_URL:http://localhost:8761/eureka/}