spring:
  datasource:
    url: ${RESOURCE_DB_DATASOURCE_URL:jdbc:postgresql://localhost:5432/resource-db}
    username: postgres
    password: postgres
app:
  url: ${SONG_SERVICE_APP_URL:http://localhost:8081/songs}