spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/resource_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
app:
  url: http://localhost:8081/songs